### ISSUE TITLE
Find Client list is populated with random entries (that do not exist)

### ISSUE THREAD

**Issue by Taeleus** [netpersona/Popcorn#37]
<img width="609" height="485" alt="Image" src="https://github.com/user-attachments/assets/36fe5398-2bc6-4fcd-99ec-f3719305342b" />

Cant seem to find my roku plex or plex app on my pc, or plex app on my phone. Installed on Unraid. Networking for Popcorn and Plex containers are set to Host. Popcorn is pointed to local IP of plex server, not using any kind of DNS filtering. Same plex account for all of it.

Out of ideas.

<img width="1080" height="889" alt="Image" src="https://github.com/user-attachments/assets/08255e79-c11b-4ac2-addb-6dbeca62a21f" />

<img width="934" height="580" alt="Image" src="https://github.com/user-attachments/assets/ed1a804a-b737-490c-a8ca-e4950c512b4e" />

<img width="506" height="469" alt="Image" src="https://github.com/user-attachments/assets/f806b72a-839c-4ccf-8738-dcf749d214f9" />

**Comment by netpersona** [comment]
The broken filter in plex_api.py (line 291) is checking r.provides == 'client' but provides is actually a list like ['player'].

Issue #38: 400 Bad Request on Web Player

- When no clients are found, web player becomes the only option
- The web player tries to generate a Plex web URL for playback
- But something about that URL generation is causing a 400 error
- However, the watch history does get logged (which is why it shows in Continue Watching), so the backend processing works - it's just the redirect/URL that fails

What's Odd

The fact that it shows up in Plex's Continue Watching at the right timestamp tells me:

- Popcorn IS successfully communicating with Plex
- The movie IS being found in the library
- The watch history logging works
- But the final step (redirecting to play the movie) fails

This suggests the custom domain detection added for web player URLs might have an edge case causing issues, or there's a URL encoding problem.

**Comment by netpersona** [comment]
When the frontend calls the /play/ endpoint and gets a successful response with a web_url, it tries to navigate the opened window to that URL (line 2258). The issue is that if the web_url is malformed or contains special characters that aren't properly encoded, the browser could return a 400 Bad Request.

Looking at the plex_api.py code, for custom domains it uses %2F encoding for the path in the URL, but this might not be sufficient. The hash fragment (#!/) and the query parameters might need additional encoding

**Comment by netpersona** [comment]
Hopefully this issue is resolved now. Can you confirm?

**Comment by MajorQuake18** [comment]
Just tried 2.1.4, still getting the 400 Bad Request error and Popcorn can't find my client devices.

**Comment by ThisGuyNeedsABeer** [comment]
Thought I was going crazy, but I also am getting random entries that do not exist. None of my preferred devices are showing up. Playback is sync'd to my server.

Edit: Running from Unraid CA, added tag `:v2.1.4` to see if any issues were resolved and it still pulls the `:v2.1.3` image. Same with the `:latest` tag

**Comment by netpersona** [comment]
Im really not sure why thats happening.. I've got what I think might be a
fix coming up, but I dont really understand the random devices issue.

Im about ti push v2.2.2 later tonight on a different branch and we'll see
if it works for you guys. Im really not sure what the issue is, bc it works
on my end. However, I did add more detailed logging, so if the issue
persists on the next update, copy your logs and paste them here so I can
see what the issue is on your end.

**Comment by ThisGuyNeedsABeer** [comment]
Happy to do so- can't wait for the latest drop.

Edit: Interestingly enough, I renamed my SHIELD from "Nvidia Shield Pro" to "SHIELD" and I get this now as the "admin" user or my Plex server owner user via Plex SSO.

<img width="1122" height="647" alt="Image" src="https://github.com/user-attachments/assets/9b3d0142-3843-487f-a825-bf840ebe7b36" />

**Edit:** Found more detail. The device's it's pulling are from my "Plex Home" users. I have 3 people in my "Plex Home" myself, my parents house, and my sister's house. The devices showing under my profile are now coming from my parent's house (In this case the Living RM Roku Ultra is my at my folks, the Android device AFTSS is at my sister's). It's also important to note they are both in use right now. If they are not in use, they do not show up as options.

If the devices can't be filtered to the profile and return all devices for the Plex home, could the list to choose be made larger so it can be scrolled?

<img width="579" height="433" alt="Image" src="https://github.com/user-attachments/assets/ddcc9c60-3d91-4566-95d0-d27a787ca850" />

**Comment by MajorQuake18** [comment]
What is the branch called that has v2.2.2? Is there a dev branch for popcorn?

**Comment by netpersona** [comment]
The v2.2.0 is the upcoming version with major changes that were requested
in the discussions tab

**Comment by netpersona** [comment]
Im taking at least the weekend off, but you should know that you can manually find your Plex Client ID by going to http://plexserver:port/clients or /status/sessions or /devices.xml. copy thatID and put it in the ID box

**Comment by Taeleus** [comment]
> /devices.xml

I am unable to hit any of those paths. I believe my server is setup behind a caddy reverse proxy and plex is setup to not allow non https connections. so I get a bunch of random 400, 401, 404 errors trying to hop around.

**Comment by netpersona** [comment]
Go to: http://YOUR_PLEX_SERVER:32400/clients?X-Plex-Token=YOUR_TOKEN
Find the device in the XML
Look for <Server machineIdentifier="XXXXX">

**Comment by netpersona** [comment]
The manual API method won't work if Plex requires HTTPS and you can't access it directly.

Start playing any movie on the device you want to use (Roku, TV, etc.)
Open Plex Web via the reverse proxy URL (their normal Plex web access)
Click "More" menu (three dots) → Dashboard
Under "Now Playing" section, they'll see their active playback
Right-click the session → Inspect (or open browser DevTools - F12)
In the Elements/Inspector tab, search for machineIdentifier
Find the attribute like: data-machine-identifier="ABC123XYZ789"

**Comment by netpersona** [comment]
I'll try to implement a fix for this in v2.2.0

**Comment by netpersona** [comment]
should be resolved with latest release.
